# Each child under "commands" becomes a dynamic command registered at runtime.
# Lines can be simple strings or structured as a list of segments made from "text"
# and "button" entries. Buttons support:
#   text         -> label shown in chat (optional formatting codes)
#   hover        -> tooltip (string or list of strings, joined with newlines)
#   commands     -> string or list; ";" also chains commands inside a string
#   run-as       -> player | console | proxy-player | proxy-console (defaults to console)
#   context      -> viewer | target (PlaceholderAPI context for text/hover)
#   append-space -> true to append a trailing space after the button
# Placeholders:
#   %player% -> the clicking player
#   %target% -> the selected target (self menus fall back to %player%)

commands:



  prefix:
    permission: chatmenu.prefix
    type: self
    message:
      - text: '&fPick your Name Color and Prefix:'
      - text: ''
      - line:
          - button:
              text: '&2[Dark Green] '
              hover: '&aSelect Dark Green'
              commands:
                - 'lp user %player% meta removeprefix 2'
                - 'lp user %player% meta addprefix 2 &2'
              notify:
                viewer: '&aSetting updated'
          - button:
              text: '&a[Green] '
              hover: '&aSelect Green'
              commands:
                - 'lp user %player% meta removeprefix 2'
                - 'lp user %player% meta addprefix 2 &a'
              notify:
                viewer: '&aSetting updated'
          - button:
              text: '&e[Yellow] '
              hover: '&aSelect Yellow'
              commands:
                - 'lp user %player% meta removeprefix 2'
                - 'lp user %player% meta addprefix 2 &e'
              notify:
                viewer: '&aSetting updated'
          - button:
              text: '&6[Orange] '
              hover: '&aSelect Orange'
              commands:
                - 'lp user %player% meta removeprefix 2'
                - 'lp user %player% meta addprefix 2 &6'
              notify:
                viewer: '&aSetting updated'
          - button:
              text: '&c[Red] '
              hover: '&aSelect Red'
              commands:
                - 'lp user %player% meta removeprefix 2'
                - 'lp user %player% meta addprefix 2 &c'
              notify:
                viewer: '&aSetting updated'
          - button:
              text: '&9[Blue] '
              hover: '&aSelect Blue'
              commands:
                - 'lp user %player% meta removeprefix 2'
                - 'lp user %player% meta addprefix 2 &9'
              notify:
                viewer: '&aSetting updated'
          - button:
              text: '&5[Purple] '
              hover: '&aSelect Purple'
              commands:
                - 'lp user %player% meta removeprefix 2'
                - 'lp user %player% meta addprefix 2 &5'
              notify:
                viewer: '&aSetting updated'
      - text: ''
      - line:
          - button:
              text: '&d[✿] '
              hover: '&dBloom with this symbol'
              commands:
                - 'lp user %player% meta removeprefix 3'
                - 'lp user %player% meta addprefix 3 "&d✿ &r"'
              notify:
                viewer: '&aSetting updated'
          - button:
              text: '&c[❤] '
              hover: '&cShow your love'
              commands:
                - 'lp user %player% meta removeprefix 3'
                - 'lp user %player% meta addprefix 3 "&c❤ &r"'
              notify:
                viewer: '&aSetting updated'
          - button:
              text: '&f[♬] '
              hover: '&fMusical vibes'
              commands:
                - 'lp user %player% meta removeprefix 3'
                - 'lp user %player% meta addprefix 3 "&f♬ &r"'
              notify:
                viewer: '&aSetting updated'
          - button:
              text: '&e[✦] '
              hover: '&eShine bright'
              commands:
                - 'lp user %player% meta removeprefix 3'
                - 'lp user %player% meta addprefix 3 "&e✦ &r"'
              notify:
                viewer: '&aSetting updated'
          - button:
              text: '&6[✯] '
              hover: '&6Add sparkle'
              commands:
                - 'lp user %player% meta removeprefix 3'
                - 'lp user %player% meta addprefix 3 "&6✯ &r"'
              notify:
                viewer: '&aSetting updated'
          - button:
              text: '&9[☄] '
              hover: '&9Cosmic style'
              commands:
                - 'lp user %player% meta removeprefix 3'
                - 'lp user %player% meta addprefix 3 "&9☄ &r"'
              notify:
                viewer: '&aSetting updated'
          - button:
              text: '&a[☀] '
              hover: '&aSunny mood'
              commands:
                - 'lp user %player% meta removeprefix 3'
                - 'lp user %player% meta addprefix 3 "&a☀ &r"'
              notify:
                viewer: '&aSetting updated'
      - text: ''
      - line:
          - button:
              text: '&c[Reset Color and Prefix]'
              hover: '&cRemove all selections'
              commands:
                - 'lp user %player% meta removeprefix 2'
                - 'lp user %player% meta removeprefix 3'
              notify:
                viewer: '&aSetting updated'




  punish:
    permission: chatmenu.punish
    type: target
    message:
      - text: '&eTargeting: &c%target%&e in group(s): &e%luckperms_inherited_groups%'
        context: target
      - text: ''
      - line:
          - button:
              text: '&e[Send Warning] '
              hover: '&eSend a warning to %target%'
              commands: []
              notify:
                target: 'Please follow the rules or you will be muted or banned permanently'
                viewer: '&fPunishment Issued'
          - button:
              text: '&e[Kick] '
              hover: '&eKick %target%'
              commands:
                - 'kick %target%'
              notify:
                viewer: '&fPunishment Issued'
      - text: ''
      - line:
          - button:
              text: '&6[Mute] '
              hover: '&6Mute %target% for 1 hour'
              commands:
                - 'mute %target% 1h'
              notify:
                viewer: '&fPunishment Issued'
          - button:
              text: '&c[Ban] '
              hover: '&cBan %target% for 1 hour'
              commands:
                - 'ban %target% 1h'
              notify:
                viewer: '&fPunishment Issued'
          - button:
              text: '&4[IP-Ban] '
              hover: '&4IP-Ban %target% for 1 hour'
              commands:
                - 'banip %target% 1h'
          - text: ' (1 Hour)'
      - text: ''
      - line:
          - button:
              text: '&6[Mute] '
              hover: '&6Mute %target% for 1 day'
              commands:
                - 'mute %target% 1d'
              notify:
                viewer: '&fPunishment Issued'
          - button:
              text: '&c[Ban] '
              hover: '&cBan %target% for 1 day'
              commands:
                - 'ban %target% 1d'
              notify:
                viewer: '&fPunishment Issued'
          - button:
              text: '&4[IP-Ban] '
              hover: '&4IP-Ban %target% for 1 day'
              commands:
                - 'banip %target% 1d'
          - text: ' (1 Day)'
      - text: ''
      - line:
          - button:
              text: '&6[Mute] '
              hover: '&6Mute %target% for 1 week'
              commands:
                - 'mute %target% 1w'
              notify:
                viewer: '&fPunishment Issued'
          - button:
              text: '&c[Ban] '
              hover: '&cBan %target% for 1 week'
              commands:
                - 'ban %target% 1w'
              notify:
                viewer: '&fPunishment Issued'
          - button:
              text: '&4[IP-Ban] '
              hover: '&4IP-Ban %target% for 1 week'
              commands:
                - 'banip %target% 1w'
          - text: ' (1 Week)'
      - text: ''
      - line:
          - button:
              text: '&6[Mute] '
              hover: '&6Mute %target% permanently'
              commands:
                - 'mute %target%'
              notify:
                viewer: '&fPunishment Issued'
          - button:
              text: '&c[Ban] '
              hover: '&cBan %target% permanently'
              commands:
                - 'ban %target%'
              notify:
                viewer: '&fPunishment Issued'
          - button:
              text: '&4[IP-Ban] '
              hover: '&4IP-Ban %target% permanently'
              commands:
                - 'banip %target%'
          - text: ' (Permanent)'
      - text: ''
      - line:
          - button:
              text: '&a[Info] '
              hover: '&aView info on %target%'
              commands:
                - 'player:/whois %target%'
          - button:
              text: '&a[Banlist] '
              hover: '&aView banlist'
              commands:
                - 'player:/banlist'
          - button:
              text: '&a[Un-Mute] '
              hover: '&aUn-Mute %target%'
              commands:
                - 'mute %target%'
              notify:
                viewer: '&fPunishment Revoked'
          - button:
              text: '&a[Un-Ban] '
              hover: '&aUn-Ban %target%'
              commands:
                - 'pardon %target%'
              notify:
                viewer: '&fPunishment Revoked'
          - button:
              text: '&a[Un-IP-Ban] '
              hover: '&aUn-IP-Ban %target%'
              commands:
                - 'pardonip %target%'
              notify:
                viewer: '&fPunishment Revoked'
      - line:
          - button:
              text: '&2[Vanish & TP] '
              hover: '&2Vanish and teleport to %target%'
              commands:
                - 'v %player%'
                - 'tp %player% %target%'
          - button:
              text: '&2[Check Alts] '
              hover: '&2Check alts of %target%'
              commands:
                - 'player:/alts %target%'
          - button:
              text: '&2[View Inventory] '
              hover: '&2View inventory of %target%'
              commands:
                - 'player:/invsee %target%'
          - button:
              text: '&2[View Enderchest] '
              hover: '&2View enderchest of %target%'
              commands:
                - 'player:/ec %target%'



  settings:
    permission: chatmenu.settings
    type: self
    message:
      - text: '&fSettings for: %player%'
      - text: ''
      - line:
          - button:
              text: '&a[Coords] '
              hover: '&aOpen coords HUD (can block other action bar messages)'
              commands:
                - 'player:/coords'
          - button:
              text: '&a[Prefix] '
              hover: '&aOpen prefix menu'
              commands:
                - 'player:/prefix'
          - button:
              text: '&a[Map] '
              hover: '&aGet link to server map'
              commands:
                - 'player:/map'
          - button:
              text: '&a[Reports] '
              hover: '&aSee instructions for player/bug reports'
              commands:
                - 'proxy:/report'
          - button:
              text: '&a[Glow] '
              hover: '&aToggle Glowing Effect'
              commands:
                - 'player:/glow'
          - button:
              text: '&a[Discord] '
              hover: '&aLink Discord account'
              commands:
                - 'player:/discordsettings'
          - button:
              text: '&a[Ignore] '
              hover: '&aIgnore Player'
              commands:
                - 'player:/ignore'

  discordsettings:
    permission: chatmenu.discordsettings
    type: self
    message:
      - line:
          - button:
              text: '&a[Discord Link] '
              hover: '&aLink Discord Account'
              commands:
                - 'player:/discord link'
          - button:
              text: '&c[Discord Unlink]'
              hover: '&cUnlink Discord Account'
              commands:
                - 'player:/discord unlink'

  map:
    permission: chatmenu.map
    type: self
    message:
      - '<hover:show_text:"Open Dynmap in your browser"><click:open_url:"https://map.00001110.xyz/"><white><underlined>https://map.00001110.xyz/</underlined></white></click></hover>'
      - text: ''
      - line:
          - button:
              text: '&a[Show on Map] '
              hover: '&aShow on Dynmap'
              commands:
                - 'player:/dynmap show'
          - button:
              text: '&c[Hide on Map]'
              hover: '&cHide on Dynmap'
              commands:
                - 'player:/dynmap hide'

  imagehelp:
    permission: chatmenu.imagehelp
    type: self
    message:
      - text: '&fUse &f&n/image create&f to create an image'
      - text: ''
      - '<white>Use a service like <hover:show_text:"Open postimages.org"><click:open_url:"https://postimages.org/"><underlined>https://postimages.org/</underlined></click></hover> for getting a link.</white>'
      - text: ''
      - text: 'Make sure to use the direct link option'
      - text: ''
      - text: 'Please note that you need to have &f&n/coords&f turned off for it to work'

  manage:
    permission: chatmenu.manage
    type: target
    message:
      - text: '&4Manage Menu'
      - text: ''
      - text: '&eTargeting: &c%target%&e in group(s): &e%luckperms_inherited_groups%'
        context: target
      - text: ''
      - line:
          - button:
              text: '&c[Restart] '
              hover: '&cRestart the server'
              commands:
                - 'restart'
          - button:
              text: '&c[Maintenance] '
              hover: '&cEnable maintenance mode'
              commands:
                - 'maintenance on'
          - button:
              text: '&c[Server Diagnostics] '
              hover: '&cCheck server diagnostics'
              commands:
                - 'player:/lag'
      - line:
          - button:
              text: '&4[Rollback Menu] '
              hover: '&4Inventory rollback of %target%'
              commands:
                - 'player:/irp restore %target%'
          - button:
              text: '&4[Rank Menu] '
              hover: '&4Manage rank of %target%'
              commands:
                - 'player:/rank %target%'
          - button:
              text: '&4[TP All] '
              hover: '&4Teleport all users to %target%'
              commands:
                - 'tpall %player%'
      - text: ''
      - line:
          - button:
              text: '&b[Cookie Time!]'
              hover: '&bGive a cookie to every player on the server'
              commands:
                - 'give * cookie 1'


  rank:
    permission: chatmenu.rank
    type: target
    message:
      - text: '&4Rank Menu'
      - text: ''
      - text: '&eTargeting: &c%target%&e in group(s): &e%luckperms_inherited_groups%'
        context: target
      - text: ''
      - line:
          - button:
              text: '&a[Promote User] '
              hover: '&aPromote user to %luckperms_next_group_on_track_main%'
              commands:
                - 'console:lp user %target% promote'
                - 'player:/rank %target%'
              notify:
                target: '&aYou have been promoted'
                viewer: '&fOperation completed'
              context: target
          - button:
              text: '&c[Demote User]'
              hover: '&cDemote user to %luckperms_previous_group_on_track_main%'
              commands:
                - 'console:lp user %target% demote'
                - 'player:/rank %target%'
              notify:
                target: '&cYou have been demoted'
                viewer: '&fOperation completed'
              context: target
